    class Tower {
        TOWER_HITS: 3000,
        TOWER_CAPACITY: 1000,
        TOWER_ENERGY_COST: 10,
        TOWER_POWER_ATTACK: 600,
        TOWER_POWER_HEAL: 400,
        TOWER_POWER_REPAIR: 800,
        TOWER_OPTIMAL_RANGE: 5,
        TOWER_FALLOFF_RANGE: 20,
        TOWER_FALLOFF: 0.75,
    };
